[package]
name    = "csrre-core"
version.workspace = true
edition.workspace = true

[dependencies]
petgraph   = { workspace = true }
egg        = { workspace = true }
smallvec   = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
log        = { workspace = true }
ndarray    = { workspace = true }
rand       = { workspace = true }
hashbrown  = { workspace = true }
fnv        = { workspace = true }
tokio      = { workspace = true }
rand_distr = "0.4"
graphica = { git = "https://github.com/symbolica-dev/graphica" }
numerica = { git = "https://github.com/symbolica-dev/numerica" }
z3 = "0.12.1"
