/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin"
#define EXEC_PREFIX "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin"
#define BINDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/bin"
#define SBINDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/sbin"
#define LIBEXECDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/libexec"
#define DATAROOTDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share"
#define DATADIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share"
#define SYSCONFDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/etc"
#define SHAREDSTATEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/com"
#define LOCALSTATEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/var"
#define RUNSTATEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/var/run"
#define INCLUDEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/doc/m4"
#define INFODIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/info"
#define HTMLDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/doc/m4"
#define DVIDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/doc/m4"
#define PDFDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/doc/m4"
#define PSDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/doc/m4"
#define LIBDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/lib"
#define LISPDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/emacs/site-lisp"
#define LOCALEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/locale"
#define MANDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/man"
#define PKGDATADIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/share/m4"
#define PKGINCLUDEDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/include/m4"
#define PKGLIBDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/lib/m4"
#define PKGLIBEXECDIR "/home/itromia/.antigravity/Relative_Active_Graph/m4_bin/libexec/m4"
